### ISSUE TITLE
Connector can register themself to the ConfigManager

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-ConfigurationManager#1]
Hi,
we had the discussion that we wanted to make Connectors scalable. For example, we want Kubernetes to automatically start new connectors when the load on one connector becomes very high. This new connector then also needs a configuration, which it should request from the config manager. For this, the Configmanager needs an API through which a new connector can register actively and dynamically.

**Comment by tmberthold** [comment]
***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Configmanager has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
