### ISSUE TITLE
Problem with contract on GET ​/api​/ui​/resource

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#105]
In the response of `GET ​/api​/ui​/resource` value and type of the rightOperand are concatenated:
```
"ids:rightOperand": {
        "@value": "12^^xsd:duration"
},
```
In the response of `GET ​/api​/ui​/resources` everything is correct:
```
"ids:rightOperand": {
                  "@value": "12",
                  "@type": "xsd:duration"
},
```

**Comment by goekhanKahriman** [comment]
The problem seems to be in the deserializer, which then adds the type specification to the value range, 
@maboeckmann was informed about the problem.

**Comment by tmberthold** [comment]
Will be fixed with infomodel-serializier 4.0.6 (release coming 26.04.).
4.0.6-SNAPSHOT will also include the fix, will be released some time next week

**Comment by goekhanKahriman** [comment]
Bug has been fixed.
However, you have to upgrade the infomodel and the serializer to version 4.0.6 at the same time.
@tmberthold what is your suggestion ?

**Comment by tmberthold** [comment]
Yes, we will probably do that then, but we have to see what changes that might lead to in the context of the connection to the DSC v4.

**Comment by tmberthold** [comment]
4.0.6 has breaking changes for us, we have to address them
