### ISSUE TITLE
Check logic behind createCustomBroker

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#123]
The _human logic_ behind the method would have to be examined once.

Background: 
BrokerService -> createCustomBroker: A custom broker is always created and persisted, even if no title is specified for the broker.
As a result, the method will never return null, but always an object of type CustomBroker.
In the BrokerController-Class it is checked if the return value is _null_, if it is _null_, a BadRequest-API return is to be given. But this can never be the case, because the CustomBroker is always created and returned in the createCustomBroker. 

`if (brokerObject != null)` -> will always be true (BrokerController -> createBroker)

https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/blob/562ac3e6d31ad7d001ac8768dfe0094914716cf0/src/main/java/de/fraunhofer/isst/configmanager/api/service/BrokerService.java#L57

https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/blob/61c4135028b05155cac0a8d1398387071c537ffe/src/main/java/de/fraunhofer/isst/configmanager/api/controller/BrokerController.java#L64

**Comment by goekhanKahriman** [comment]
Pull Request #126
