### ISSUE TITLE
Updating a resource in CM deletes its representation

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-ConfigurationManager#125]
When a resource with a representation other than 'local' is updated, then its description is deleted.
Steps to reproduce:
1. Create a resource with a **http-get representation** using the DSC API.
2. Reload Data Offering > IDS Resources page in the CM to make the new resource visible in the CM.
3. Click the edit button for this resource to edit it.
4. Click the save button.
The resource representation is now overridden and of **type local**. Can be checked using DSC API /admin/api/resources/{resource-id}/{representation-id} endpoint.

**Comment by tmberthold** [comment]
Will be fixed together with https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/63 in the new version. In the demo-case the default local is used when editing the resource as fallback.

**Comment by tmberthold** [comment]
Fixed on dev.
