### ISSUE TITLE
Unit Tests for all Controller

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager#127]
There is a need to test the individual controllers to ensure that the individual APIs offered for the frontend work successfully.

This issue should be worked on continuously and therefore should not be closed.

**Comment by goekhanKahriman** [comment]
This issue will be further developed in the following branch: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/127-unit-tests

**Comment by tmberthold** [comment]
Test coverage has been increased to at least 50% by integration into the Dataspace Connector.

***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
