### ISSUE TITLE
Pull Docker Images from Docker Registry

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager#133]
The configmanager must be able to download docker images from a registry.

For this, the following dependency can be included in the pom.xml:
https://mvnrepository.com/artifact/com.github.docker-java/docker-java/3.2.8

**Comment by tmberthold** [comment]
AppStore / App support will be integrated into the Dataspace Connector.

***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
