### ISSUE TITLE
Usermanagement

### ISSUE THREAD

**Issue by ob-silva** [International-Data-Spaces-Association/IDS-ConfigurationManager#145]
The ConfigurationManager should support usermanagement in the API, preferably with Keycloak and OAuth2.

**Comment by tmberthold** [comment]
Will be integrated into the Dataspace Connector.

***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
