### ISSUE TITLE
Incorrect redirection from base path 

### ISSUE THREAD

**Issue by sTb1337** [International-Data-Spaces-Association/IDS-ConfigurationManager#166]
I deployed an IDS-ConfigurationManager 7.0.0 instance on an hyperscaler.

When accessing the base url for Open-API/Swagger-UI https://cfg-manager-provider.*.shoot.canary.k8s-hana.ondemand.com/swagger-ui/ it redirects me to https://cfg-manager-provider.*.shoot.canary.k8s-hana.ondemand.com/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config where I see the following error: "No API definition provided." "{"messages":["attribute openapi is not of type `object`"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (string) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"#","pointer":""},"instance":{"pointer":""}}]}"

I compared it to my previous instance of an older version of IDS-ConfigurationManager which redirected me to *.shoot.canary.k8s-hana.ondemand.com/swagger-ui/index.html?url=/v3/api-docs/#/

After changing index.html?configUrl=/v3/api-docs/swagger-config to index.html?url=/v3/api-docs/#/ it worked.

GET
​/api​/ui​/route​/deploymethod
Returns the route deploy method for all routes

PUT
​/api​/ui​/route​/deploymethod
Updates the route deploy method for all routes

**Comment by tmberthold** [comment]
Thanks for the feedback, will take a look.

**Comment by tmberthold** [comment]
After a little research, this seems to be the default behavior of the Swagger-UI. If no specific url is given, it tries to call the config-page. The config-page can be set to another page by settings, but the wrong redirection from the base path (for our use case) cannot be prevented. Accordingly, the information in the CM-readme is correct, which explains the direct access:
`To interact with the running application, the provided endpoints at the Swagger UI can be used. The Swagger UI is available at: http://localhost:8081/swagger-ui/index.html?url=/v3/api-docs/`
