### ISSUE TITLE
Integration with Broker

### ISSUE THREAD

**Issue by mikhail-gordienko** [International-Data-Spaces-Association/IDS-ConfigurationManager#174]
Hello!

In this [video](https://www.youtube.com/watch?v=zk0N6u5ewOA), the  ConfigurationManager sends connectors self-description to the Broker and as a result on the Broker side, we can see registered resources. I am wondering how it is implemented because looking on the v7.0.0 of the ConfigurationManager I do not see any HTTP integration. There are only local state updates in BrokerService. 

```
public void sentSelfDescToBroker(final URI brokerId) {
        final var customBroker = getById(brokerId);
        customBroker.setRegisteredResources(
                resourceService.getResources().stream().map(Resource::getId).map(URI::toString)
                        .collect(Collectors.toList())
        );
        customBrokerRepository.save(customBroker);
    }
```

And there is no scheduled process that syncs local broker status with the remote one.

**Comment by tmberthold** [comment]
The ConfigManager notifies the Dataspace Connector, which then sends the IDS-messages. The ConfigManager does not send IDS-messages to other participants of the data ecosystem at any time, this is done exclusively by the actual connector (Dataspace Connector here) itself.

**Comment by tmberthold** [comment]
As an example, here is the call to the Connector to register at a broker:
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/blob/4ae0496f942f85cd0483cd02a07f829465ced887/src/main/java/de/fraunhofer/isst/configmanager/api/controller/BrokerController.java#L158

**Comment by mikhail-gordienko** [comment]
Ok, I see now, thank you!
