### ISSUE TITLE
[Shared DM] Wrong resource language mapping

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-ConfigurationManager#2]
When creating a resource, the language property does not reach the DSC correctly. An example: I set the language to DE and the DSC responds EN when requesting the resource's metadata.

Setup: ConfigManager `feature/Routenhandling` and GUI `fake`

**Comment by goekhanKahriman** [comment]
The resource creation in the config manager has a Language field to specify the language. Currently, the ResourceMetadata class has no Language attribute and is automatically set to English. Therefore, the input via the UI is not accepted.

**Comment by goekhanKahriman** [comment]
This issue can be closed after this issue by the DSC is https://github.com/FraunhoferISST/DataspaceConnector/issues/114 solved

**Comment by tmberthold** [comment]
Problem still persists. 
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/21ac858700628fb421e17c1b88a1393794399163/src/main/java/de/fraunhofer/isst/dataspaceconnector/services/utils/IdsUtils.java#L84

**Comment by tmberthold** [comment]
Fixed with Dataspace Connector v6.0.0.

***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Configmanager has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
