### ISSUE TITLE
Representation URL set to default when no authentication has been provided

### ISSUE THREAD

**Issue by MikhailGordienk** [International-Data-Spaces-Association/IDS-ConfigurationManager#200]
Hello!

When creating a resource using an existing backend connection without auth credentials, the resource representation gets created with default UEL (example.com). Please take a look [here](https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/blob/32f2fc9e61c6b957d1a721462a79a4fd9b60303f/src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/util/ResourceMapper.java#L168).

Tested with v7.0.0

**Comment by tmberthold** [comment]
Hello and thank you for the feedback!
This error will be fixed with the upcoming version .

**Comment by tmberthold** [comment]
ConfigManager has been integrated directly into the Dataspace Connector (v6.0.0), should be fixed by that.

***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
