### ISSUE TITLE
noProxyUri not set on PUT ​/api​/ui​/configmodel​/proxy

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#26]
Setting noProxyUri as parameter of `PUT ​/api​/ui​/configmodel​/proxy` (Swagger or UI)
`GET ​/api​/ui​/configmodel` & `GET ​/api​/ui​/configmodel​/proxy` do not contain any noProxyUri data.

**Comment by goekhanKahriman** [comment]
fixed in feauter-Branch
