### ISSUE TITLE
Configuration not forwarded

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-ConfigurationManager#29]
When editing and saving the connector's settings in the GUI, the properties are not forwareded. Due to the different Infomodel versions, the serializers would have a conflict at this point. Nevertheless, after extracting the route part, the configmodel should still be accepted by the DSC. Have you tried that? @goekhanKahriman

**Comment by goekhanKahriman** [comment]
The changes made to the configuration manager settings are now sent to the DSC. As a temporary solution, app routes are not sent because the infomodel versions of the configuration manager and the dataspace connector do not match.
