### ISSUE TITLE
Cut backend access url 

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-ConfigurationManager#3]
When setting the access url of a backend connection, it does not reach the DSC correctly. The url was cut off and the connector is not able to retreive the data source.

Setup: ConfigManager `feature/Routenhandling` and GUI `fake`

**Comment by tmberthold** [comment]
**Do you have an example of the URL that doesn't work, which we could use for testing purposes?**

Here's what I can recreate in a similar context:

Steps:
1. **ConfigManager-UI**: Add Backed Connection
![image](https://user-images.githubusercontent.com/75306992/109963149-5da2ab80-7cec-11eb-8a78-163bb77ea6d2.png)

2. **ConfigManager-UI**: Triggers a POST to the ConfigManager with a cut off URL (something has gone wrong here in the meantime):
![image](https://user-images.githubusercontent.com/75306992/109963256-7ca13d80-7cec-11eb-8f7f-48641ee7f300.png)

3. **ConfigManager**: Receives the already cut off URL and saves it (my own local built-in debug messages):
![image](https://user-images.githubusercontent.com/75306992/109963407-ace8dc00-7cec-11eb-8d84-582667e8a74c.png)

4. **ConfigManager-UI**: Displays accordingly the already previously cut off URL stored in the ConfigManager:
![image](https://user-images.githubusercontent.com/75306992/109963525-cc800480-7cec-11eb-8ada-db777442d211.png)

If I run the same via the Swagger UI of **ConcifgManager** itself, this example above works fine. I get the impression it might be the UI.

**Comment by BastianWel** [comment]
It's because '&' is used for parameter seperartion on API calls.
They need to be escaped.
I will fix this in the UI.

**Comment by tmberthold** [comment]
Thanks for the quick help!

The example shown above now works with the develop branchs of the ConfigManager and the ConfigManager-UI.

If there is another use case, please let us know.
