### ISSUE TITLE
Broker communication errors not handled

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-ConfigurationManager#30]
Errors are not properly handled (at least not in the GUI @BastianWel)? Two examples:

- I register the DSC at the broker with an invalid DAT (intended). I get a rejection message from the broker, that is correctly responded by the connector. Still, the GUI told me that the registration has been successful and the button is marked as `unregister`. How can we improve that? Response code changes in the DSC? Response validation in the Configmanager?
- Same when the registration of a resource at the broker failed (with valid DAT). I can then unregister it and again get an error from the broker, because the resource was not known to it.

When testing the implementation, you may check the success at the broker's GUI: https://broker.ids.isst.fraunhofer.de/query/.

**Comment by goekhanKahriman** [comment]
The BrokerUIController is refactored for improved error handling for the ui
