### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager#37]
All exceptions would have to be caught in the source code and logged. This is not the case in some places, as an example:
ConfigmodelService -> Line: 44/45 ...

**Comment by tmberthold** [comment]
The specific use case mentioned here has now been resolved, other adaptions to the logging-structure will be addressed in the future.

**Comment by tmberthold** [comment]
Added incoming API Call logging from the GUI to the Backend, other logs will be addressed with future updates and refactorings:

![image](https://user-images.githubusercontent.com/75306992/111686633-90d75580-8829-11eb-960f-c1d12f80ae6d.png)
