### ISSUE TITLE
Support http connection to dataspace connector

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-ConfigurationManager#38]
Currently the configuration manager connects to the dataspace connector with https only. Please make this configurable to be able to connect with http too.

**Comment by tmberthold** [comment]
Hello and thank you for the feedback! We will take a closer look.

**Comment by tmberthold** [comment]
Functionality will be implemented, both for Docker environment, and for JAR environment.

**Comment by tmberthold** [comment]
Branch: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/38-support-http-dsc

**Comment by tmberthold** [comment]
Is now included in 6.1.0-SNAPSHOT (currently on dev-branch, not released yet).

application.properties: dataspace.communication.ssl=true/false
docker-env: DATASPACE_COMMUNICATION_SSL=true/false (will overwrite app.prop)

Log entry shows at CM startup which connection type will be used for communication with DSC:

![image](https://user-images.githubusercontent.com/75306992/113311604-c855ff80-9309-11eb-95dd-4c87640c3736.png)

vs

![image](https://user-images.githubusercontent.com/75306992/113311625-cc821d00-9309-11eb-8396-96f1a1f74425.png)
