### ISSUE TITLE
Ressource handling issues

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-ConfigurationManager#4]
When deleting the resource via the ConfigManager GUI, it is not deleted in the DSC. Afterwards, I cannot create a new resource, because ConfigManager and GUI are throwing errors.

Setup: ConfigManager `feature/Routenhandling` and GUI `fake`

**Comment by tmberthold** [comment]
Should now work using the two development branches.

If there are still use cases causing problems, please let us know.
