### ISSUE TITLE
Existing connector resources are not (always) loaded

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#44]
Reproduce:
- Start UI, Conifigmanager & DataSpaceConnector, create a resource via UI. 
- Stop Configmanager, delete configmanager database and restart.
- Resource from Connector is sometimes not loaded at startup.

@tmberthold @goekhanKahriman

**Comment by tmberthold** [comment]
fixed on branch bugfixes, will be released soon
