### ISSUE TITLE
Check which APIs are really used

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#51]
There seem to be APIs in CM which are not used by the GUI (for example POST /configmodel to create a new configmodel, only update is used). Check which APIs are not used at all.

**Comment by ob-silva** [comment]
The following API routes aren't used by the Configmanager UI:

![image](https://user-images.githubusercontent.com/77329033/112306972-b12b6800-8ca0-11eb-8af5-737656983ea9.png)

**Comment by tmberthold** [comment]
Is now being addressed, will be a new major version though:
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/51-clean-up-API

**Comment by tmberthold** [comment]
Pull Request: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/pull/113
