### ISSUE TITLE
Tests fail on master branch

### ISSUE THREAD

**Issue by ctoscano-eu** [International-Data-Spaces-Association/IDS-ConfigurationManager#52]
Installed the software (from master branch). Runned mvn clean package. Tests fail. See enclosing log file.
[log.txt](https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/files/6165794/log.txt)

**Comment by tmberthold** [comment]
Thanks for the feedback, will take a look.

**Comment by tmberthold** [comment]
We are about to release a new version, I would ask then to test this version instead as soon as it is available. I'll get back to you on this.

**Comment by ctoscano-eu** [comment]
ok. thank you.

**Comment by tmberthold** [comment]
We just released version 6.0.0 (docker-image or also on master-branch).

Could you please try to use this version in combination with the latest GUI-release?

The version of CM 4.1.0 mentioned in the logs is an older version, where this could happen.

**Comment by tmberthold** [comment]
Will be closed now due to no new known error message and we are preparing version 7.0.0 (refactored APIs). If there are still problems with the latest current version 6, please let us know.
