### ISSUE TITLE
POST /api/ui/broker/delete/resource not working

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#56]
After calling `POST /api/ui/broker/delete/resource` for one resource and broker, `GET /api​/ui​/broker​/resource​/information` still returns this broker for this resource.

**Comment by tmberthold** [comment]
Should be fixed on branch bugfixes with commit 4ea008a6b999454776a52580e3c17f2b973ff030
