### ISSUE TITLE
Multiple bindings for SPARQL query

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#58]
This might not be our fault, but it needs to be clarified in conjunction with the Connector and GUI, so it is noted here:

Under certain circumstances the parser of the infomodel throws an error message when displaying resources. 

So far, we assume that it is due to the same Representation-ID in both OfferedResources and RequestedResources of the connector. As a result, two mimetypes with different IDs are noted for one Representation-ID, which causes the parser to crash.

Needs further investigation to see if this issue can be resolved or is it due to something else

```
13:15:59.192 [http-nio-8080-exec-9] ERROR - Multiple bindings for SPARQL query which should only have one binding. Input contains multiple values for a field which may occur only once.
java.io.IOException: Multiple bindings for SPARQL query which should only have one binding. Input contains multiple values for a field which may occur only once.
at de.fraunhofer.iais.eis.ids.jsonld.Parser.handleObject(Parser.java:453) ~[infomodel-serializer-4.0.2.jar!/:?]
at de.fraunhofer.iais.eis.ids.jsonld.Parser.handleObject(Parser.java:527) ~[infomodel-serializer-4.0.2.jar!/:?]
at de.fraunhofer.iais.eis.ids.jsonld.Parser.handleObject(Parser.java:527) ~[infomodel-serializer-4.0.2.jar!/:?]
```

**Comment by goekhanKahriman** [comment]
This cannot be addressed in configmanager.
The only solution here is to not have the same id in the representations under the offered resources and requested resources
