### ISSUE TITLE
Camel Routes Integration

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager#6]
The created Camel Route implementations have to be integrated and tested in Configmanager.

**Comment by goekhanKahriman** [comment]
The issue is processed under the branch: "Camel-Integration"

**Comment by tmberthold** [comment]
New Branch name: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/6-camel-integration

**Comment by goekhanKahriman** [comment]
Merged the latest state of dev-Branch into this branch
