### ISSUE TITLE
Editing a resource

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#60]
It looks like we are not getting the source-type of the backend connection when the resource-update-api is called through the GUI. The format of the policy on update-api-call also needs to be checked. Could both cause problems when editing a resource in the GUI.

**Comment by tmberthold** [comment]
Topic Source-Type: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager-UI/issues/22

**Comment by goekhanKahriman** [comment]
fixed that edits to resources are not saved
commit-id: 8c59cb2dff8fb69bb13ed343fbb3c8cead6a05aa
