### ISSUE TITLE
Add API required param for source-type in endpoint handling

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#63]
Endpoint APIs need additional param to set the source-type of an endpoint.

**Comment by tmberthold** [comment]
Branch: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/63-source-type-api

**Comment by ob-silva** [comment]
I've added sourceType as a required parameter for the following routes:
POST /connector/endpoint and POST /generic/endpoint 

Pull request at https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/pull/120

**Comment by goekhanKahriman** [comment]
I am not sure and think that the API POST /connector/endpoint don't needs a SourceType property @ob-silva .
Maybe @tmberthold can enlighten us here

**Comment by tmberthold** [comment]
I will have a look, please do not merge the pull-request yet. :)

**Comment by goekhanKahriman** [comment]
I have made two more changes. The first change concerns the resource representation. These no longer have a sourceType property. Furthermore the createBackendSource method now uses the endpoint instead of the representation to get the sourceType.

**Comment by tmberthold** [comment]
fixed and merged into dev
