### ISSUE TITLE
Coordinated always 0 on GET ​/api​/ui​/approute​/step​/endpoint​/info

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#64]
X/Y coordinates on `POST /api​/ui​/approute​/step` do not seem to be saved.
Returned values are always 0.
This can be reproduced with Swagger.

@goekhanKahriman

**Comment by goekhanKahriman** [comment]
fixed in branch "bugfix" with commit-id: 8681b55daa833f06727596012027057e270a2e7b
