### ISSUE TITLE
Umlauts still incorrect on GET ​/api​/ui​/resource

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#65]
Umlauts are now returned correctly on `GET /api​/ui​/resources`, but on `GET ​/api​/ui​/resource` (used for "edit resource") umlauts are still wrong.

@tmberthold

**Comment by tmberthold** [comment]
Thanks for the feedback! Actually in principle the problem occurs everywhere where the Infomodel-Serializer is used in between.

**Comment by tmberthold** [comment]
Branch: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/65-default-jvm-charset

JVM charset, in which the JAR is running, needs to be forced to use UTF-8, else it can default to windows-1252 depending on operating system, which combination doesn't work with the serializer and umlauts.

**Comment by tmberthold** [comment]
Docker: Using of UTF-8 now enforced for JVM at docker entrypoint

Local Jar: Needs to be checked locally, which encoding is used when starting the JAR via Java -jar (info is printed at App-Start which JVM default-charset is set). UTF-8 should be used to use umlauts with the serializer

https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/commit/3a7c87c7ae1543bef8b691227d8b630930e3a488

---

Possible local solution, if `-Dfile.encoding` can't be changed: Set System-Var on Windows to default use UTF-8 for JVMs (JAVA_TOOL_OPTIONS).

![image](https://user-images.githubusercontent.com/75306992/112463072-16935d80-8d62-11eb-89cc-1834d2817f60.png)

---

Infomodel-Serializer will print a warning in a future release, if JVM-charset != UTF-8:

![image](https://user-images.githubusercontent.com/75306992/112463458-91f50f00-8d62-11eb-9561-e7b0aaf1bb0d.png)
