### ISSUE TITLE
Language is always set to EN when creating a resource.

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#66]
Regardless of the language, which is set on `POST /api​/ui​/resource` and `POST ​/api​/ui​/resource​/representation`, the language in the created resources is set to EN.

**Comment by tmberthold** [comment]
Closed due to duplicate: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/2
