### ISSUE TITLE
Error on GET ​/api​/ui​/broker​/resource​/information

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#70]
When no brokers exists, GET ​/api​/ui​/broker​/resource​/information returns 
```
ERROR 400: can't parse JSON.  Raw result: 
Could not get registration status for resource
```

**Comment by goekhanKahriman** [comment]
fixed with commit-id: 5c780c7dc938eda2c96c9ac5a423cf78c9b3d89e
Empty array will be returned instead of bad request response
