### ISSUE TITLE
Representation Source Type is not persisted

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-ConfigurationManager#71]
If I create a new resource in the data offerings then the Source Type is not persisted. No matter what source type I chose. After saving the newly created resource, it is gone.

**Comment by tmberthold** [comment]
Hello and thanks for the message! The dropdown doesn't actually belong there overall, as it belongs directly to a backend-connection and not where it currently is. We are changing that right now.

https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager-UI/issues/24

**Comment by goekhanKahriman** [comment]
This bug will be solved with https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/63 .
