### ISSUE TITLE
[Shared DM] Save App-Routes in CM

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#78]
After restarting the CM, the created routes are no longer available.

**Comment by CarstenWhz** [comment]
I stumbled across it too. It is more critical than you think, because even if a simple resource is created, a route is also created. If you restart CM, there are then consequential errors that are confusing at first.

**Comment by goekhanKahriman** [comment]
@CarstenWhz 
The problem that the app routes no longer appear after a restart will be fixed with the shared data management.
Therefore, it is not useful to fix the problem for the current configmanager version.

**Comment by tmberthold** [comment]
Should be resolved by integration into the Dataspace Connector v6.

***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
