### ISSUE TITLE
[Broker] Resources must be able to be registered individually with the broker

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#84]
When unregistering a resource in its settings at a broker, the resource is still registered at the broker (even if it is reregistered at the broker)

**Comment by goekhanKahriman** [comment]
Will be discussed further in the following branch:  https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/84_broker_resource_registration

**Comment by goekhanKahriman** [comment]
The problem is probably with the broker. With the new infomodel update a new mandatory field - DefaultEndpoint, which is a ConnectorEndpoint, has been added. According to @maboeckmann , it could be that the broker still has old records that do not have the mandatory field.

**Comment by tmberthold** [comment]
Should be resolved by integration into the Dataspace Connector.

***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
