### ISSUE TITLE
[Broker] Checkmark validation in resource settings for unregistered brokers

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#85]
If the connector is not registered at a broker, but you want to register a resource at the broker in the resource-settings, there is no error message that this is not possible because the entire connector is not registered. (maybe directly solvable via GUI, which could query the registration status of the brokers in the resource-settings before displaying the checkboxes)

**Comment by tmberthold** [comment]
According to discussion today implemented by UI, brokers are not displayed, if the connector is not registered. (?) Needs to be tested and to be asked again if it is indeed implemented.

**Comment by goekhanKahriman** [comment]
Has been solved in the configmanger ui. When creating a resource, the broker is only displayed if you have registered with the connector previously.
