### ISSUE TITLE
[Shared DM] Path specification to concrete file within folder structure in resource

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#86]
Since the backend-connection is to be reused in the GUI, the complete path to the specific file would have to be specified in the resources/representation-tab.

**Comment by goekhanKahriman** [comment]
The problem is that the DSC does not have an attribute in its BackendSource class to make a detailed path description. The CM and the UI could implement this, but the information would be lost in the DSC and only the accessURL for the backend connection would be persisted.

**Comment by tmberthold** [comment]
(ids:path vs ids:acessURL)

**Comment by tmberthold** [comment]
***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
