### ISSUE TITLE
[Broker] Wrong broker registration status

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#89]
If `POST /api​/ui​/broker​/register` is called without a network connection, then it returns ` "success": true`.
Also, the status of the broker from the API call above on `GET /api​/ui​/brokers` is set to `"brokerStatus": "REGISTERED"`, although this is not possible.

**Comment by tmberthold** [comment]
Fixed on Dev-Branch and will be released with the next version.
