### ISSUE TITLE
Option to disable HTTPS connection to the Datapase Connector

### ISSUE THREAD

**Issue by DominikPinsel** [International-Data-Spaces-Association/IDS-ConfigurationManager#91]
Although the Dataspace Connector has enabled HTTPS by default, its possible to disable it using environment variables. Like this the (by default) non trusted dataspace connector certificate can be disabled and we are able to secure the connection to the Dataspace Connector ourself.

As for the Configuration Manager, we are not able to disable the HTTPS connection to the Dataspace Connector from outside the code (DataspaceConnectorClient.java). We would appreciate an option in the application properties to disable HTTPS.

<sub> Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by tmberthold** [comment]
Will be added in a future release, closing Issue because of duplicate to: https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/38

**Comment by tmberthold** [comment]
Is now included in 6.1.0-SNAPSHOT (currently on dev-branch).

application.properties: dataspace.communication.ssl=true/false
docker-env: DATASPACE_COMMUNICATION_SSL=true/false (will overwrite app.prop)

Log entry shows at CM startup which connection type will be used for communication with DSC:

![image](https://user-images.githubusercontent.com/75306992/113311604-c855ff80-9309-11eb-95dd-4c87640c3736.png)

vs

![image](https://user-images.githubusercontent.com/75306992/113311625-cc821d00-9309-11eb-8396-96f1a1f74425.png)

**Comment by DominikPinsel** [comment]
Great! :) Thanks a lot for the fast reply and sorry that I didn't look close enough for duplicates. I will try out the build next week!

**Comment by tmberthold** [comment]
No problem!
Just let us know if you have any feedback, we will be happy to help!
