### ISSUE TITLE
Refactor DataspaceConnectorClient

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#96]
Class contains way too much code, maybe split the individual method-functionalities into several subclasses, which are then called along their domain (broker, resource etc.).

**Comment by goekhanKahriman** [comment]
The dataspaceconnectorclient is now splited into three different client classes and offers a better view for the different approaches. Also an abstract class is created which contains the common features of all three client classes
Is merged into the development branch
